/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        sage: {
          50: '#f4f8f4',
          100: '#e6efe6',
          200: '#cdddcd',
          300: '#a8c4a8',
          400: '#7da37d',
          500: '#5a855a',
          600: '#456b45',
          700: '#385638',
          800: '#2e4530',
          900: '#273a29',
          950: '#142016',
        },
        cream: {
          50: '#fdfbf7',
          100: '#faf5ec',
          200: '#f4e9d4',
          300: '#ecd9b5',
          400: '#e0c08c',
          500: '#d4a566',
          600: '#c08a4f',
          700: '#9e6c41',
          800: '#80573a',
          900: '#6a4833',
        },
        gold: {
          50: '#fbf8ef',
          100: '#f6edd3',
          200: '#ecd9a5',
          300: '#e0bf6e',
          400: '#d4a44c',
          500: '#c08e3a',
          600: '#a3702f',
          700: '#825629',
          800: '#6c4727',
          900: '#5b3c24',
        },
        dark: {
          50: '#f6f6f6',
          100: '#e2e2e2',
          200: '#c4c4c4',
          300: '#9d9d9d',
          400: '#717171',
          500: '#525252',
          600: '#3d3d3d',
          700: '#2d2d2d',
          800: '#1f1f1f',
          900: '#141414',
          950: '#0a0a0a',
        },
        chart: {
          1: 'hsl(var(--chart-1))',
          2: 'hsl(var(--chart-2))',
          3: 'hsl(var(--chart-3))',
          4: 'hsl(var(--chart-4))',
          5: 'hsl(var(--chart-5))',
        },
      },
      backgroundImage: {
        'gradient-brand': 'linear-gradient(135deg, #5a855a 0%, #456b45 50%, #385638 100%)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        'slide-in': {
          from: { opacity: '0', transform: 'translateX(-12px)' },
          to: { opacity: '1', transform: 'translateX(0)' },
        },
        'pulse-ring': {
          '0%': { boxShadow: '0 0 0 0 rgba(90, 133, 90, 0.4)' },
          '70%': { boxShadow: '0 0 0 10px rgba(90, 133, 90, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(90, 133, 90, 0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.4s ease-out',
        'slide-in': 'slide-in 0.3s ease-out',
        'pulse-ring': 'pulse-ring 2s infinite',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
